fix: add .org cors domains to allowed origins
freeCodeCamp/boilerplate-bcrypt pull request #2
Opened 2018-05-05 14:54 UTC by clandau

Fixes issue #1 by adding https://beta.freecodecamp.org and https://www.freecodecamp.org as allowed origins in freeCodeCamp/fcctesting.js.  This makes testing work for the beta BCrypt hashing challenges, starting with this challenge: https://beta.freecodecamp.org/en/challenges/information-security-with-helmetjs/understand-bcrypt-hashes.

2018-05-05 15:45 UTC, Greenheart reviewed
Thanks again @clandau 😄 

I looked into how the other projects solve this and found [this PR](https://github.com/freeCodeCamp/boilerplate-advancednode/pull/1/). By using a regex instead of strings, we can future proof the boilerplate in case we change sub-domains in the future. I think [something similar to this](https://github.com/freeCodeCamp/boilerplate-advancednode/pull/1/files#diff-73618e16fffda0d9f71489aead148b04R40) would be a good solution here.

@Bouncey was asked to review the other PR, so if he gets time, perhaps he could review this one as well. Otherwise, someone in https://gitter.im/FreeCodeCamp/Contributors could probably help you if you ask.

Have a nice day, and happy coding! 👩‍💻

2018-05-05 15:56 UTC, clandau commented
That sounds good @Greenheart I could work on that.

2018-05-08 09:01 UTC, Bouncey requested changes

2018-05-08 09:01 UTC, Bouncey commented on freeCodeCamp/fcctesting.js
> +const allowedOriginsMatcher = /^https?:\/\/([\w-]+\.)*freecodecamp.org/;
Currently this regex will allow origins such as `https://www.freecodecamp-org.evil`

Changing it to ` /^https?:\/\/([\w-]+\.)*freecodecamp\.org/`  will enforce a `.` after `freecodecamp`

2018-05-08 13:11 UTC, Bouncey commented
Thanks for this @clandau :+1:

2018-05-08 13:11 UTC, merged