fix: remove instruction hints and update readme
freeCodeCamp/boilerplate-bcrypt pull request #8
Opened 2020-10-12 03:54 UTC by moT01

Remove instruction hints and update readme.

Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39720

2020-10-12 11:29 UTC, Sky020 commented
Any particular reason for all of the empty lines in `server.js`?

2020-10-12 14:59 UTC, moT01 commented
It's where users will enter their code. Wasn't quite sure what to do there - I [added this in the instructions that would be on learn.](https://github.com/freeCodeCamp/freeCodeCamp/pull/39954/files#diff-fbc3268d190b5b05a9b39fa406894a01R17) - Any thoughts?

2020-10-12 16:46 UTC, Sky020 requested changes
I would prefer a heading like this

2020-10-12 16:46 UTC, Sky020 commented on README.md
> +# [bcrypt Challenges](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/understand-bcrypt-hashes)
```suggestion
# [Information Security with HelmetJS - BCrypt](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/understand-bcrypt-hashes)
```

2020-10-12 16:48 UTC, moT01 commented on README.md
> +# [bcrypt Challenges](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/understand-bcrypt-hashes)
me too 👍

2020-10-12 16:50 UTC, Sky020 approved these changes
LGTM 👍 

Thanks for the back-and-forth, Tom

2020-11-05 03:12 UTC, RandellDawson approved these changes
LGTM  We can merge this once PR https://github.com/freeCodeCamp/freeCodeCamp/pull/39954 hits production.

2020-11-13 15:12 UTC, merged

2020-11-13 15:12 UTC, Sky020 commented
Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉